image: atomfrede/gitlab-ci-jhipster-stack

cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules
        - .maven
stages:
    - build
    - test
    - package
    - release
    - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export MAVEN_USER_HOME=`pwd`/.maven
    - npm install

maven-build:
    stage: build
    script: ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME

gulp-build:
    stage: build
    script:
        - gulp build
maven-test:
    stage: test
    script:
        - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/surefire-reports/*
gatling-test:
    stage: test
    allow_failure: true
    script:
        - ./mvnw gatling:execute -Dmaven.repo.local=$MAVEN_USER_HOME
    before_script:
        - npm install
        - ./mvnw &
    artifacts:
        paths:
            - target/gatling/*
maven-package:
    stage: package
    script:
        - ./mvnw package -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/*.war
